export SPRING_DATASOURCE_URL=jdbc:postgresql://SAMPLE:5432/SAMPLE
export SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
export SPRING_DATASOURCE_USERNAME=SAMPLE
export SPRING_DATASOURCE_PASSWORD=SAMPLE

java -jar springbootdeveloper-0.0.1-SNAPSHOT.jar